import type { AnimalDef, AnimalId, ShopAnimalId } from './types';

const animalDefs: Record<AnimalId, AnimalDef> = {
  BarnCat: {
    id: 'BarnCat',
    name: 'Barn Cat',
    costMischief: null,
    mischief: 1,
    hay: 0,
    noisy: false,
    noisyMitigation: 0,
    givesHermitCrabBonus: false,
    givesDraftPonyBonus: false,
    inShop: false,
    abilityKind: 'none',
    tier: 'common',
  },
  FeralGoat: {
    id: 'FeralGoat',
    name: 'Feral Goat',
    costMischief: null,
    mischief: 2,
    hay: 0,
    noisy: true,
    noisyMitigation: 0,
    givesHermitCrabBonus: false,
    givesDraftPonyBonus: false,
    inShop: false,
    abilityKind: 'none',
    tier: 'common',
  },
  PotBelliedPig: {
    id: 'PotBelliedPig',
    name: 'Pot-Bellied Pig',
    costMischief: null,
    mischief: 0,
    hay: 1,
    noisy: false,
    noisyMitigation: 0,
    givesHermitCrabBonus: false,
    givesDraftPonyBonus: false,
    inShop: false,
    abilityKind: 'none',
    tier: 'common',
  },
  Bunny: {
    id: 'Bunny',
    name: 'Bunny',
    costMischief: 4,
    mischief: 1,
    hay: 0,
    noisy: false,
    noisyMitigation: 1,
    givesHermitCrabBonus: false,
    givesDraftPonyBonus: false,
    inShop: true,
    abilityKind: 'noisy_mitigation',
    tier: 'common',
  },
  Hen: {
    id: 'Hen',
    name: 'Hen',
    costMischief: 4,
    mischief: -1,
    hay: 2,
    noisy: false,
    noisyMitigation: 0,
    givesHermitCrabBonus: false,
    givesDraftPonyBonus: false,
    inShop: true,
    abilityKind: 'none',
    tier: 'common',
  },
  WildBoar: {
    id: 'WildBoar',
    name: 'Wild Boar',
    costMischief: 3,
    mischief: 4,
    hay: 0,
    noisy: true,
    noisyMitigation: 0,
    givesHermitCrabBonus: false,
    givesDraftPonyBonus: false,
    inShop: true,
    abilityKind: 'none',
    tier: 'common',
  },
  HermitCrab: {
    id: 'HermitCrab',
    name: 'Hermit Crab',
    costMischief: 4,
    mischief: 1,
    hay: 0,
    noisy: false,
    noisyMitigation: 0,
    givesHermitCrabBonus: true,
    givesDraftPonyBonus: false,
    inShop: true,
    abilityKind: 'bonus_per_empty_slot',
    tier: 'common',
  },
  DraftPony: {
    id: 'DraftPony',
    name: 'Draft Pony',
    costMischief: 5,
    mischief: 1,
    hay: 0,
    noisy: false,
    noisyMitigation: 0,
    givesHermitCrabBonus: false,
    givesDraftPonyBonus: true,
    inShop: true,
    abilityKind: 'bonus_per_barn_cat',
    tier: 'common',
  },
  StruttingPeacock: {
    id: 'StruttingPeacock',
    name: 'Strutting Peacock',
    costMischief: 5,
    mischief: 3,
    hay: 2,
    noisy: true,
    noisyMitigation: 0,
    givesHermitCrabBonus: false,
    givesDraftPonyBonus: false,
    inShop: true,
    abilityKind: 'none',
    tier: 'common',
  },
  MilkmaidGoat: {
    id: 'MilkmaidGoat',
    name: 'Milkmaid Goat',
    costMischief: 5,
    mischief: 4,
    hay: -1,
    noisy: false,
    noisyMitigation: 0,
    givesHermitCrabBonus: false,
    givesDraftPonyBonus: false,
    inShop: true,
    abilityKind: 'none',
    tier: 'common',
  },
  HoneyBee: {
    id: 'HoneyBee',
    name: 'Honey Bee',
    costMischief: 7,
    mischief: 2,
    hay: 0,
    noisy: false,
    noisyMitigation: 1,
    givesHermitCrabBonus: false,
    givesDraftPonyBonus: false,
    inShop: true,
    abilityKind: 'noisy_mitigation',
    tier: 'common',
  },
  // Sprint 003: active-ability animals
  Sheepdog: {
    id: 'Sheepdog',
    name: 'Sheepdog',
    costMischief: 4,
    mischief: 2,
    hay: 0,
    noisy: false,
    noisyMitigation: 0,
    givesHermitCrabBonus: false,
    givesDraftPonyBonus: false,
    inShop: true,
    abilityKind: 'peek',
    tier: 'common',
  },
  StableHand: {
    id: 'StableHand',
    name: 'Stable Hand',
    costMischief: 4,
    mischief: 0,
    hay: 0,
    noisy: false,
    noisyMitigation: 0,
    givesHermitCrabBonus: false,
    givesDraftPonyBonus: false,
    inShop: true,
    abilityKind: 'boot',
    tier: 'common',
  },
  BorderCollie: {
    id: 'BorderCollie',
    name: 'Border Collie',
    costMischief: 5,
    mischief: 2,
    hay: -1,
    noisy: false,
    noisyMitigation: 0,
    givesHermitCrabBonus: false,
    givesDraftPonyBonus: false,
    inShop: true,
    abilityKind: 'fetch',
    tier: 'common',
  },
  CheerfulLamb: {
    id: 'CheerfulLamb',
    name: 'Cheerful Lamb',
    costMischief: 5,
    mischief: 1,
    hay: 0,
    noisy: false,
    noisyMitigation: 0,
    givesHermitCrabBonus: false,
    givesDraftPonyBonus: false,
    inShop: true,
    abilityKind: 'refresh',
    tier: 'common',
  },
  // Sprint 003: Legendary animals
  GoldenGoose: {
    id: 'GoldenGoose',
    name: 'Golden Goose',
    costMischief: 30,
    mischief: 3,
    hay: 1,
    noisy: false,
    noisyMitigation: 0,
    givesHermitCrabBonus: false,
    givesDraftPonyBonus: false,
    inShop: true,
    abilityKind: 'none',
    tier: 'legendary',
  },
  GiantOx: {
    id: 'GiantOx',
    name: 'Giant Ox',
    costMischief: 35,
    mischief: 2,
    hay: 1,
    noisy: false,
    noisyMitigation: 0,
    givesHermitCrabBonus: false,
    givesDraftPonyBonus: false,
    inShop: true,
    abilityKind: 'none',
    tier: 'legendary',
  },
  Jackalope: {
    id: 'Jackalope',
    name: 'Jackalope',
    costMischief: 40,
    mischief: 4,
    hay: 0,
    noisy: false,
    noisyMitigation: 0,
    givesHermitCrabBonus: false,
    givesDraftPonyBonus: false,
    inShop: true,
    abilityKind: 'none',
    tier: 'legendary',
  },
  Thunderbird: {
    id: 'Thunderbird',
    name: 'Thunderbird',
    costMischief: 45,
    mischief: 5,
    hay: 0,
    noisy: false,
    noisyMitigation: 0,
    givesHermitCrabBonus: false,
    givesDraftPonyBonus: false,
    inShop: true,
    abilityKind: 'none',
    tier: 'legendary',
  },
  SilverMare: {
    id: 'SilverMare',
    name: 'Silver Mare',
    costMischief: 45,
    mischief: 2,
    hay: 0,
    noisy: false,
    noisyMitigation: 1,
    givesHermitCrabBonus: false,
    givesDraftPonyBonus: false,
    inShop: true,
    abilityKind: 'noisy_mitigation',
    tier: 'legendary',
  },
  LuckyToad: {
    id: 'LuckyToad',
    name: 'Lucky Toad',
    costMischief: 50,
    mischief: 1,
    hay: 3,
    noisy: false,
    noisyMitigation: 0,
    givesHermitCrabBonus: false,
    givesDraftPonyBonus: false,
    inShop: true,
    abilityKind: 'none',
    tier: 'legendary',
  },
  GreatStag: {
    id: 'GreatStag',
    name: 'Great Stag',
    costMischief: 50,
    mischief: 3,
    hay: 0,
    noisy: false,
    noisyMitigation: 0,
    givesHermitCrabBonus: false,
    givesDraftPonyBonus: false,
    inShop: true,
    abilityKind: 'boot',
    tier: 'legendary',
  },
  BarnDragon: {
    id: 'BarnDragon',
    name: 'Barn Dragon',
    costMischief: 55,
    mischief: 4,
    hay: 0,
    noisy: false,
    noisyMitigation: 0,
    givesHermitCrabBonus: false,
    givesDraftPonyBonus: false,
    inShop: true,
    abilityKind: 'fetch',
    tier: 'legendary',
  },
};

export const STARTING_HERD = [
  { animalId: 'BarnCat', quantity: 4 },
  { animalId: 'FeralGoat', quantity: 4 },
  { animalId: 'PotBelliedPig', quantity: 2 },
] as const satisfies ReadonlyArray<{ animalId: AnimalId; quantity: number }>;

export const SHOP_ANIMALS = [
  animalDefs.Bunny,
  animalDefs.Hen,
  animalDefs.WildBoar,
  animalDefs.HermitCrab,
  animalDefs.DraftPony,
  animalDefs.StruttingPeacock,
  animalDefs.MilkmaidGoat,
  animalDefs.HoneyBee,
  animalDefs.Sheepdog,
  animalDefs.StableHand,
  animalDefs.BorderCollie,
  animalDefs.CheerfulLamb,
] as const;

export const LEGENDARY_ANIMALS = [
  animalDefs.GoldenGoose,
  animalDefs.GiantOx,
  animalDefs.Jackalope,
  animalDefs.Thunderbird,
  animalDefs.SilverMare,
  animalDefs.LuckyToad,
  animalDefs.GreatStag,
  animalDefs.BarnDragon,
] as const;

export const SHOP_ANIMAL_IDS = SHOP_ANIMALS.map(
  (animal) => animal.id,
) as ReadonlyArray<ShopAnimalId>;

export const LEGENDARY_ANIMAL_IDS = LEGENDARY_ANIMALS.map(
  (animal) => animal.id,
) as ReadonlyArray<ShopAnimalId>;

export const ALL_ANIMALS = Object.values(animalDefs) as ReadonlyArray<AnimalDef>;

export const getAnimalDef = (animalId: AnimalId): AnimalDef => {
  return animalDefs[animalId];
};

export const isShopAnimalId = (animalId: AnimalId): animalId is ShopAnimalId => {
  return (
    SHOP_ANIMAL_IDS.includes(animalId as ShopAnimalId) ||
    LEGENDARY_ANIMAL_IDS.includes(animalId as ShopAnimalId)
  );
};
