export const LAYOUT = {
  CANVAS: {
    REF_WIDTH: 390,
    REF_HEIGHT: 844,
  },
  SLOT: {
    WIDTH: 96,
    HEIGHT: 104,
    GAP: 12,
    COLUMNS: 3,
    START_Y: 156,
    ROW_GAP: 14,
    MAX_ROWS: 3,
  },
  BARN: {
    HEADER_HEIGHT: 126,
    FLOOR_Y: 544,
    FLOOR_HEIGHT: 120,
    DECK_SIZE: 72,
  },
  FARMHOUSE: {
    X: 24,
    Y: 560,
    WIDTH: 142,
    HEIGHT: 116,
    WINDOW: {
      WIDTH: 34,
      HEIGHT: 24,
      OFFSET_X: 54,
      OFFSET_Y: 28,
    },
  },
  ACTION_BAR: {
    X: 20,
    Y: 758,
    WIDTH: 350,
    HEIGHT: 56,
    GAP: 14,
  },
  INFO_PANEL: {
    X: 12,
    Y: 556,
    WIDTH: 366,
    HEIGHT: 180,
  },
  SUMMARY: {
    X: 20,
    Y: 120,
    WIDTH: 350,
    HEIGHT: 580,
  },
  SHOP: {
    GRID_X: 20,
    GRID_Y: 152,
    GRID_COLUMNS: 2,
    CARD_WIDTH: 170,
    CARD_HEIGHT: 108,
    GRID_GAP_X: 10,
    GRID_GAP_Y: 10,
  },
  BADGE: {
    DIAMETER: 32,
  },
  TAP_TARGET_MIN: 44,
} as const;

export const PALETTE = {
  SKY_TOP: 0x10243f,
  SKY_MID: 0x173a5e,
  SKY_LOW: 0x295c7a,
  SUNSET_GLOW: 0xc4724a,
  DUSTY_ROSE: 0xb07070,
  WARM_SHADOW: 0x3d1f1a,
  NIGHT_PLUM: 0x1a0e2e,
  BARN_DARK: 0x6b3027,
  BARN_BASE: 0x8b3a3a,
  BARN_LIGHT: 0xa5563d,
  BARN_HIGHLIGHT: 0xb8654e,
  BARN_KNOT: 0x4a1e14,
  STRAW: 0xd9a441,
  STRAW_HIGHLIGHT: 0xf1c86a,
  STRAW_DARK: 0x9e7a2e,
  STRAW_SHADOW: 0x8a6420,
  PARCHMENT: 0xf0e1be,
  PARCHMENT_STROKE: 0x8f7651,
  PAPER_GRAIN: 0xd8cba6,
  NOISY_CARD: 0xd78f8a,
  WARNING: 0xffbe4d,
  BUST: 0xd94b3d,
  DUST_MOTE: 0xd4a574,
  SPARK_RED: 0xff4433,
  SPARK_ORANGE: 0xff8844,
  GOLD_SPARKLE: 0xffd700,
  OVERLAY_WOOD: 0x2a1810,
  SUCCESS: 0x5c9b5d,
  BUTTON_PRIMARY: 0x4a7c59,
  BUTTON_SECONDARY: 0x3f5866,
  BUTTON_DISABLED: 0x5e5e5e,
  TEXT_DARK: '#241611',
  TEXT_LIGHT: '#f8f3e5',
  SHOP_BG: 0x5c4033,
  // Sprint 003: new palette entries
  LEGENDARY_GOLD: 0xd4a017,
  LEGENDARY_BORDER: 0xffd700,
  ABILITY_ACTIVE: 0x2d6a9f,
  ABILITY_PASSIVE: 0x4a7c59,
  ABILITY_TRIGGERED: 0xc4982a,
} as const;

export const ANIMATION = {
  DRAW_SLIDE_MS: 220,
  DRAW_POP_MS: 120,
  NOISE_SHAKE_MS: 100,
  WARNING_GLOW_MS: 800,
  BUST_SHAKE_MS: 150,
  BUST_OVERLAY_MS: 300,
  SCORE_LINE_MS: 300,
  SCORE_STAGGER_MS: 100,
  PURCHASE_FEEDBACK_MS: 200,
  BUTTON_FLASH_MS: 120,
  // Sprint 003: new animation timings
  STAT_POP_MS: 120,
  INFO_PANEL_REVEAL_MS: 160,
  INFO_PANEL_DISMISS_MS: 120,
  ABILITY_PULSE_MS: 700,
  BOOT_HIGHLIGHT_MS: 500,
  FETCH_LIST_MS: 180,
  REFRESH_PULSE_MS: 200,
  LEGENDARY_GLOW_MS: 900,
  LEGENDARY_SHINE_MS: 1400,
  WIN_BURST_MS: 450,
  WIN_OVERLAY_RISE_MS: 260,
  BOOT_REMOVAL_MS: 200,
  LONG_PRESS_MS: 300,
  LONG_PRESS_MOVE_THRESHOLD: 10,
  SCENE_FADE_MS: 200,
} as const;

export const DEPTH = {
  BG: 0,
  WALL: 10,
  RAFTER: 20,
  FLOOR: 30,
  FARMHOUSE: 40,
  SLOTS: 50,
  CARD_SHADOWS: 60,
  CARDS: 70,
  LEGENDARY_FX: 80,
  DUST: 90,
  HUD: 100,
  BUTTONS: 110,
  VIGNETTE: 120,
  OVERLAYS: 200,
  OVERLAY_PARTICLES: 210,
} as const;

export const GAME_LIMITS = {
  STARTING_CAPACITY: 5,
  MAX_CAPACITY: 8,
  CAPACITY_COSTS: {
    6: 2,
    7: 3,
    8: 4,
  },
  MAX_SHOP_STOCK_PER_ANIMAL: 3,
  LEGENDARY_WIN_COUNT: 3,
} as const;

export const TEXTURES = {
  CARD_PARCHMENT: 'ui-card-parchment',
  CARD_NOISY: 'ui-card-noisy',
  CARD_LEGENDARY: 'ui-card-legendary',
  SLOT_EMPTY: 'ui-slot-empty',
  SLOT_OCCUPIED: 'ui-slot-occupied',
  BADGE_MISCHIEF: 'ui-badge-mischief',
  BADGE_HAY: 'ui-badge-hay',
  BADGE_MISCHIEF_LG: 'ui-badge-mischief-lg',
  BADGE_HAY_LG: 'ui-badge-hay-lg',
  BADGE_NOISY_STRIPE: 'ui-badge-noisy-stripe',
  BADGE_STAR: 'ui-badge-star',
  ABILITY_STRIP_ACTIVE: 'ui-ability-strip-active',
  ABILITY_STRIP_PASSIVE: 'ui-ability-strip-passive',
  ABILITY_STRIP_TRIGGERED: 'ui-ability-strip-triggered',
  INFO_PANEL_BG: 'ui-info-panel-bg',
  NOISE_DOT_EMPTY: 'ui-noise-dot-empty',
  NOISE_DOT_FILLED: 'ui-noise-dot-filled',
  BUTTON_PRIMARY: 'ui-button-primary',
  BUTTON_SECONDARY: 'ui-button-secondary',
  BUTTON_DISABLED: 'ui-button-disabled',
  BUTTON_DANGER: 'ui-button-danger',
  BARN_PLANK: 'env-barn-plank',
  BARN_PLANK_TILE: 'env-barn-plank-tile',
  RAFTER: 'env-rafter',
  FLOOR_STRAW: 'env-floor-straw',
  FLOOR_STRAW_TILE: 'env-floor-straw-tile',
  FARMHOUSE: 'env-farmhouse',
  WINDOW_GLOW: 'env-window-glow',
  DECK_BACK: 'env-deck-back',
  OVERLAY_BG: 'ui-overlay-bg',
  CARD_SHADOW: 'ui-card-shadow',
  VIGNETTE: 'env-vignette',
  TRADING_POST_BG: 'env-trading-post-bg',
  FX_DUST: 'fx-dust',
  FX_SPARK: 'fx-spark',
  FX_CHAFF: 'fx-chaff',
  FX_PUFF: 'fx-puff',
  LOCK_ICON: 'ui-lock-icon',
} as const;

export const DOM_PHASE = {
  READY_TO_DRAW: 'ready_to_draw',
  ANIMATING_DRAW: 'animating_draw',
  PLAYER_DECISION: 'player_decision',
  WARNING: 'warning',
  ABILITY_DECISION: 'ability_decision',
  BUST: 'bust',
  NIGHT_SUMMARY: 'night_summary',
  WIN: 'win',
  SHOP: 'shop',
} as const;
